export enum GS1Field {
  SSCC = "sscc",
  GTIN = "gtin",
  CONTENT = "content",
  BATCH = "batch",
  PROD_DATE = "prodDate",
  DUE_DATE = "dueDate",
  PACK_DATE = "packDate",
  BEST_BEFORE = "bestBefore",
  SELL_BY = "sellBy",
  EXP_DATE = "expDate",
  VARIANT = "variant",
  SERIAL = "serial",
  HIBCC = "hibcc",
  TPX = "tpx",
  ADDITIONAL_PRODUCT_ID = "additionalProductID",
  CUSTOMER_PART_NUMBER = "customerPartNumber",
  MADE_TO_ORDER = "madeToOrder",
  PACKAGING = "packaging",
  SECONDARY_SERIAL_NUMBER = "secondarySerialNumber",
  REF_SOURCE = "refSource",
  GDTI = "gdti",
  GLN_EXTENSION = "glnExtension",
  GCN = "gcn",
  VARIABLE_COUNT = "variableCount",
  NET_WEIGHT_KG_0 = "netWeightKg0",
  NET_WEIGHT_KG_1 = "netWeightKg1",
  NET_WEIGHT_KG_2 = "netWeightKg2",
  NET_WEIGHT_KG_3 = "netWeightKg3",
  NET_WEIGHT_KG_4 = "netWeightKg4",
  NET_WEIGHT_KG_5 = "netWeightKg5",
  LENGTH_METERS_0 = "lengthMeters0",
  LENGTH_METERS_1 = "lengthMeters1",
  LENGTH_METERS_2 = "lengthMeters2",
  LENGTH_METERS_3 = "lengthMeters3",
  LENGTH_METERS_4 = "lengthMeters4",
  LENGTH_METERS_5 = "lengthMeters5",
  WIDTH_METERS_0 = "widthMeters0",
  WIDTH_METERS_1 = "widthMeters1",
  WIDTH_METERS_2 = "widthMeters2",
  WIDTH_METERS_3 = "widthMeters3",
  WIDTH_METERS_4 = "widthMeters4",
  WIDTH_METERS_5 = "widthMeters5",
  HEIGHT_METERS_0 = "heightMeters0",
  HEIGHT_METERS_1 = "heightMeters1",
  HEIGHT_METERS_2 = "heightMeters2",
  HEIGHT_METERS_3 = "heightMeters3",
  HEIGHT_METERS_4 = "heightMeters4",
  HEIGHT_METERS_5 = "heightMeters5",
  AREA_SQUARE_METERS_0 = "areaSquareMeters0",
  AREA_SQUARE_METERS_1 = "areaSquareMeters1",
  AREA_SQUARE_METERS_2 = "areaSquareMeters2",
  AREA_SQUARE_METERS_3 = "areaSquareMeters3",
  AREA_SQUARE_METERS_4 = "areaSquareMeters4",
  AREA_SQUARE_METERS_5 = "areaSquareMeters5",
  NET_VOLUME_LITERS_0 = "netVolumeLiters0",
  NET_VOLUME_LITERS_1 = "netVolumeLiters1",
  NET_VOLUME_LITERS_2 = "netVolumeLiters2",
  NET_VOLUME_LITERS_3 = "netVolumeLiters3",
  NET_VOLUME_LITERS_4 = "netVolumeLiters4",
  NET_VOLUME_LITERS_5 = "netVolumeLiters5",
  NET_VOLUME_CUBIC_METERS_0 = "netVolumeCubicMeters0",
  NET_VOLUME_CUBIC_METERS_1 = "netVolumeCubicMeters1",
  NET_VOLUME_CUBIC_METERS_2 = "netVolumeCubicMeters2",
  NET_VOLUME_CUBIC_METERS_3 = "netVolumeCubicMeters3",
  NET_VOLUME_CUBIC_METERS_4 = "netVolumeCubicMeters4",
  NET_VOLUME_CUBIC_METERS_5 = "netVolumeCubicMeters5",
  NET_WEIGHT_LB_0 = "netWeightLb0",
  NET_WEIGHT_LB_1 = "netWeightLb1",
  NET_WEIGHT_LB_2 = "netWeightLb2",
  NET_WEIGHT_LB_3 = "netWeightLb3",
  NET_WEIGHT_LB_4 = "netWeightLb4",
  NET_WEIGHT_LB_5 = "netWeightLb5",
  LENGTH_INCHES_0 = "lengthInches0",
  LENGTH_INCHES_1 = "lengthInches1",
  LENGTH_INCHES_2 = "lengthInches2",
  LENGTH_INCHES_3 = "lengthInches3",
  LENGTH_INCHES_4 = "lengthInches4",
  LENGTH_INCHES_5 = "lengthInches5",
  LENGTH_FEET_0 = "lengthFeet0",
  LENGTH_FEET_1 = "lengthFeet1",
  LENGTH_FEET_2 = "lengthFeet2",
  LENGTH_FEET_3 = "lengthFeet3",
  LENGTH_FEET_4 = "lengthFeet4",
  LENGTH_FEET_5 = "lengthFeet5",
  LENGTH_YARDS_0 = "lengthYards0",
  LENGTH_YARDS_1 = "lengthYards1",
  LENGTH_YARDS_2 = "lengthYards2",
  LENGTH_YARDS_3 = "lengthYards3",
  LENGTH_YARDS_4 = "lengthYards4",
  LENGTH_YARDS_5 = "lengthYards5",
  WIDTH_INCHES_0 = "widthInches0",
  WIDTH_INCHES_1 = "widthInches1",
  WIDTH_INCHES_2 = "widthInches2",
  WIDTH_INCHES_3 = "widthInches3",
  WIDTH_INCHES_4 = "widthInches4",
  WIDTH_INCHES_5 = "widthInches5",
  WIDTH_FEET_0 = "widthFeet0",
  WIDTH_FEET_1 = "widthFeet1",
  WIDTH_FEET_2 = "widthFeet2",
  WIDTH_FEET_3 = "widthFeet3",
  WIDTH_FEET_4 = "widthFeet4",
  WIDTH_FEET_5 = "widthFeet5",
  WIDTH_YARDS_0 = "widthYards0",
  WIDTH_YARDS_1 = "widthYards1",
  WIDTH_YARDS_2 = "widthYards2",
  WIDTH_YARDS_3 = "widthYards3",
  WIDTH_YARDS_4 = "widthYards4",
  WIDTH_YARDS_5 = "widthYards5",
  HEIGHT_INCHES_0 = "heightInches0",
  HEIGHT_INCHES_1 = "heightInches1",
  HEIGHT_INCHES_2 = "heightInches2",
  HEIGHT_INCHES_3 = "heightInches3",
  HEIGHT_INCHES_4 = "heightInches4",
  HEIGHT_INCHES_5 = "heightInches5",
  HEIGHT_FEET_0 = "heightFeet0",
  HEIGHT_FEET_1 = "heightFeet1",
  HEIGHT_FEET_2 = "heightFeet2",
  HEIGHT_FEET_3 = "heightFeet3",
  HEIGHT_FEET_4 = "heightFeet4",
  HEIGHT_FEET_5 = "heightFeet5",
  HEIGHT_YARDS_0 = "heightYards0",
  HEIGHT_YARDS_1 = "heightYards1",
  HEIGHT_YARDS_2 = "heightYards2",
  HEIGHT_YARDS_3 = "heightYards3",
  HEIGHT_YARDS_4 = "heightYards4",
  HEIGHT_YARDS_5 = "heightYards5",
  GROSS_WEIGHT_KG_0 = "grossWeightKg0",
  GROSS_WEIGHT_KG_1 = "grossWeightKg1",
  GROSS_WEIGHT_KG_2 = "grossWeightKg2",
  GROSS_WEIGHT_KG_3 = "grossWeightKg3",
  GROSS_WEIGHT_KG_4 = "grossWeightKg4",
  GROSS_WEIGHT_KG_5 = "grossWeightKg5",
  LENGTH_METERS_LOG_0 = "lengthMetersLog0",
  LENGTH_METERS_LOG_1 = "lengthMetersLog1",
  LENGTH_METERS_LOG_2 = "lengthMetersLog2",
  LENGTH_METERS_LOG_3 = "lengthMetersLog3",
  LENGTH_METERS_LOG_4 = "lengthMetersLog4",
  LENGTH_METERS_LOG_5 = "lengthMetersLog5",
  WIDTH_METERS_LOG_0 = "widthMetersLog0",
  WIDTH_METERS_LOG_1 = "widthMetersLog1",
  WIDTH_METERS_LOG_2 = "widthMetersLog2",
  WIDTH_METERS_LOG_3 = "widthMetersLog3",
  WIDTH_METERS_LOG_4 = "widthMetersLog4",
  WIDTH_METERS_LOG_5 = "widthMetersLog5",
  HEIGHT_METERS_LOG_0 = "heightMetersLog0",
  HEIGHT_METERS_LOG_1 = "heightMetersLog1",
  HEIGHT_METERS_LOG_2 = "heightMetersLog2",
  HEIGHT_METERS_LOG_3 = "heightMetersLog3",
  HEIGHT_METERS_LOG_4 = "heightMetersLog4",
  HEIGHT_METERS_LOG_5 = "heightMetersLog5",
  AREA_SQUARE_INCHES_0 = "areaSquareInches0",
  AREA_SQUARE_INCHES_1 = "areaSquareInches1",
  AREA_SQUARE_INCHES_2 = "areaSquareInches2",
  AREA_SQUARE_INCHES_3 = "areaSquareInches3",
  AREA_SQUARE_INCHES_4 = "areaSquareInches4",
  AREA_SQUARE_INCHES_5 = "areaSquareInches5",
  AREA_SQUARE_FEET_0 = "areaSquareFeet0",
  AREA_SQUARE_FEET_1 = "areaSquareFeet1",
  AREA_SQUARE_FEET_2 = "areaSquareFeet2",
  AREA_SQUARE_FEET_3 = "areaSquareFeet3",
  AREA_SQUARE_FEET_4 = "areaSquareFeet4",
  AREA_SQUARE_FEET_5 = "areaSquareFeet5",
  AREA_SQUARE_YARDS_0 = "areaSquareYards0",
  AREA_SQUARE_YARDS_1 = "areaSquareYards1",
  AREA_SQUARE_YARDS_2 = "areaSquareYards2",
  AREA_SQUARE_YARDS_3 = "areaSquareYards3",
  AREA_SQUARE_YARDS_4 = "areaSquareYards4",
  AREA_SQUARE_YARDS_5 = "areaSquareYards5",
  AREA_SQUARE_METERS_LOG_0 = "areaSquareMetersLog0",
  AREA_SQUARE_METERS_LOG_1 = "areaSquareMetersLog1",
  AREA_SQUARE_METERS_LOG_2 = "areaSquareMetersLog2",
  AREA_SQUARE_METERS_LOG_3 = "areaSquareMetersLog3",
  AREA_SQUARE_METERS_LOG_4 = "areaSquareMetersLog4",
  AREA_SQUARE_METERS_LOG_5 = "areaSquareMetersLog5",
  NET_WEIGHT_OUNCES_0 = "netWeightOunces0",
  NET_WEIGHT_OUNCES_1 = "netWeightOunces1",
  NET_WEIGHT_OUNCES_2 = "netWeightOunces2",
  NET_WEIGHT_OUNCES_3 = "netWeightOunces3",
  NET_WEIGHT_OUNCES_4 = "netWeightOunces4",
  NET_WEIGHT_OUNCES_5 = "netWeightOunces5",
  NET_VOLUME_QUARTS_0 = "netVolumeQuarts0",
  NET_VOLUME_QUARTS_1 = "netVolumeQuarts1",
  NET_VOLUME_QUARTS_2 = "netVolumeQuarts2",
  NET_VOLUME_QUARTS_3 = "netVolumeQuarts3",
  NET_VOLUME_QUARTS_4 = "netVolumeQuarts4",
  NET_VOLUME_QUARTS_5 = "netVolumeQuarts5",
  NET_VOLUME_GALLONS_0 = "netVolumeGallons0",
  NET_VOLUME_GALLONS_1 = "netVolumeGallons1",
  NET_VOLUME_GALLONS_2 = "netVolumeGallons2",
  NET_VOLUME_GALLONS_3 = "netVolumeGallons3",
  NET_VOLUME_GALLONS_4 = "netVolumeGallons4",
  NET_VOLUME_GALLONS_5 = "netVolumeGallons5",
  VOLUME_CUBIC_INCHES_0 = "volumeCubicInches0",
  VOLUME_CUBIC_INCHES_1 = "volumeCubicInches1",
  VOLUME_CUBIC_INCHES_2 = "volumeCubicInches2",
  VOLUME_CUBIC_INCHES_3 = "volumeCubicInches3",
  VOLUME_CUBIC_INCHES_4 = "volumeCubicInches4",
  VOLUME_CUBIC_INCHES_5 = "volumeCubicInches5",
  VOLUME_CUBIC_FEET_0 = "volumeCubicFeet0",
  VOLUME_CUBIC_FEET_1 = "volumeCubicFeet1",
  VOLUME_CUBIC_FEET_2 = "volumeCubicFeet2",
  VOLUME_CUBIC_FEET_3 = "volumeCubicFeet3",
  VOLUME_CUBIC_FEET_4 = "volumeCubicFeet4",
  VOLUME_CUBIC_FEET_5 = "volumeCubicFeet5",
  VOLUME_CUBIC_YARDS_0 = "volumeCubicYards0",
  VOLUME_CUBIC_YARDS_1 = "volumeCubicYards1",
  VOLUME_CUBIC_YARDS_2 = "volumeCubicYards2",
  VOLUME_CUBIC_YARDS_3 = "volumeCubicYards3",
  VOLUME_CUBIC_YARDS_4 = "volumeCubicYards4",
  VOLUME_CUBIC_YARDS_5 = "volumeCubicYards5",
  VOLUME_CUBIC_METERS_LOG_0 = "volumeCubicMetersLog0",
  VOLUME_CUBIC_METERS_LOG_1 = "volumeCubicMetersLog1",
  VOLUME_CUBIC_METERS_LOG_2 = "volumeCubicMetersLog2",
  VOLUME_CUBIC_METERS_LOG_3 = "volumeCubicMetersLog3",
  VOLUME_CUBIC_METERS_LOG_4 = "volumeCubicMetersLog4",
  VOLUME_CUBIC_METERS_LOG_5 = "volumeCubicMetersLog5",
  GROSS_WEIGHT_LB_0 = "grossWeightLb0",
  GROSS_WEIGHT_LB_1 = "grossWeightLb1",
  GROSS_WEIGHT_LB_2 = "grossWeightLb2",
  GROSS_WEIGHT_LB_3 = "grossWeightLb3",
  GROSS_WEIGHT_LB_4 = "grossWeightLb4",
  GROSS_WEIGHT_LB_5 = "grossWeightLb5",
  LENGTH_INCHES_LOG_0 = "lengthInchesLog0",
  LENGTH_INCHES_LOG_1 = "lengthInchesLog1",
  LENGTH_INCHES_LOG_2 = "lengthInchesLog2",
  LENGTH_INCHES_LOG_3 = "lengthInchesLog3",
  LENGTH_INCHES_LOG_4 = "lengthInchesLog4",
  LENGTH_INCHES_LOG_5 = "lengthInchesLog5",
  LENGTH_FEET_LOG_0 = "lengthFeetLog0",
  LENGTH_FEET_LOG_1 = "lengthFeetLog1",
  LENGTH_FEET_LOG_2 = "lengthFeetLog2",
  LENGTH_FEET_LOG_3 = "lengthFeetLog3",
  LENGTH_FEET_LOG_4 = "lengthFeetLog4",
  LENGTH_FEET_LOG_5 = "lengthFeetLog5",
  LENGTH_YARDS_LOG_0 = "lengthYardsLog0",
  LENGTH_YARDS_LOG_1 = "lengthYardsLog1",
  LENGTH_YARDS_LOG_2 = "lengthYardsLog2",
  LENGTH_YARDS_LOG_3 = "lengthYardsLog3",
  LENGTH_YARDS_LOG_4 = "lengthYardsLog4",
  LENGTH_YARDS_LOG_5 = "lengthYardsLog5",
  WIDTH_INCHES_LOG_0 = "widthInchesLog0",
  WIDTH_INCHES_LOG_1 = "widthInchesLog1",
  WIDTH_INCHES_LOG_2 = "widthInchesLog2",
  WIDTH_INCHES_LOG_3 = "widthInchesLog3",
  WIDTH_INCHES_LOG_4 = "widthInchesLog4",
  WIDTH_INCHES_LOG_5 = "widthInchesLog5",
  WIDTH_FEET_LOG_0 = "widthFeetLog0",
  WIDTH_FEET_LOG_1 = "widthFeetLog1",
  WIDTH_FEET_LOG_2 = "widthFeetLog2",
  WIDTH_FEET_LOG_3 = "widthFeetLog3",
  WIDTH_FEET_LOG_4 = "widthFeetLog4",
  WIDTH_FEET_LOG_5 = "widthFeetLog5",
  WIDTH_YARDS_LOG_0 = "widthYardsLog0",
  WIDTH_YARDS_LOG_1 = "widthYardsLog1",
  WIDTH_YARDS_LOG_2 = "widthYardsLog2",
  WIDTH_YARDS_LOG_3 = "widthYardsLog3",
  WIDTH_YARDS_LOG_4 = "widthYardsLog4",
  WIDTH_YARDS_LOG_5 = "widthYardsLog5",
  HEIGHT_INCHES_LOG_0 = "heightInchesLog0",
  HEIGHT_INCHES_LOG_1 = "heightInchesLog1",
  HEIGHT_INCHES_LOG_2 = "heightInchesLog2",
  HEIGHT_INCHES_LOG_3 = "heightInchesLog3",
  HEIGHT_INCHES_LOG_4 = "heightInchesLog4",
  HEIGHT_INCHES_LOG_5 = "heightInchesLog5",
  HEIGHT_FEET_LOG_0 = "heightFeetLog0",
  HEIGHT_FEET_LOG_1 = "heightFeetLog1",
  HEIGHT_FEET_LOG_2 = "heightFeetLog2",
  HEIGHT_FEET_LOG_3 = "heightFeetLog3",
  HEIGHT_FEET_LOG_4 = "heightFeetLog4",
  HEIGHT_FEET_LOG_5 = "heightFeetLog5",
  HEIGHT_YARDS_LOG_0 = "heightYardsLog0",
  HEIGHT_YARDS_LOG_1 = "heightYardsLog1",
  HEIGHT_YARDS_LOG_2 = "heightYardsLog2",
  HEIGHT_YARDS_LOG_3 = "heightYardsLog3",
  HEIGHT_YARDS_LOG_4 = "heightYardsLog4",
  HEIGHT_YARDS_LOG_5 = "heightYardsLog5",
  GROSS_WEIGHT_OUNCES_0 = "grossWeightOunces0",
  GROSS_WEIGHT_OUNCES_1 = "grossWeightOunces1",
  GROSS_WEIGHT_OUNCES_2 = "grossWeightOunces2",
  GROSS_WEIGHT_OUNCES_3 = "grossWeightOunces3",
  GROSS_WEIGHT_OUNCES_4 = "grossWeightOunces4",
  GROSS_WEIGHT_OUNCES_5 = "grossWeightOunces5",
  NET_VOLUME_FLUID_OUNCES_0 = "netVolumeFluidOunces0",
  NET_VOLUME_FLUID_OUNCES_1 = "netVolumeFluidOunces1",
  NET_VOLUME_FLUID_OUNCES_2 = "netVolumeFluidOunces2",
  NET_VOLUME_FLUID_OUNCES_3 = "netVolumeFluidOunces3",
  NET_VOLUME_FLUID_OUNCES_4 = "netVolumeFluidOunces4",
  NET_VOLUME_FLUID_OUNCES_5 = "netVolumeFluidOunces5",
  GROSS_VOLUME_QUARTS_0 = "grossVolumeQuarts0",
  GROSS_VOLUME_QUARTS_1 = "grossVolumeQuarts1",
  GROSS_VOLUME_QUARTS_2 = "grossVolumeQuarts2",
  GROSS_VOLUME_QUARTS_3 = "grossVolumeQuarts3",
  GROSS_VOLUME_QUARTS_4 = "grossVolumeQuarts4",
  GROSS_VOLUME_QUARTS_5 = "grossVolumeQuarts5",
  GROSS_VOLUME_GALLONS_0 = "grossVolumeGallons0",
  GROSS_VOLUME_GALLONS_1 = "grossVolumeGallons1",
  GROSS_VOLUME_GALLONS_2 = "grossVolumeGallons2",
  GROSS_VOLUME_GALLONS_3 = "grossVolumeGallons3",
  GROSS_VOLUME_GALLONS_4 = "grossVolumeGallons4",
  GROSS_VOLUME_GALLONS_5 = "grossVolumeGallons5",
  VOLUME_CUBIC_INCHES_LOG_0 = "volumeCubicInchesLog0",
  VOLUME_CUBIC_INCHES_LOG_1 = "volumeCubicInchesLog1",
  VOLUME_CUBIC_INCHES_LOG_2 = "volumeCubicInchesLog2",
  VOLUME_CUBIC_INCHES_LOG_3 = "volumeCubicInchesLog3",
  VOLUME_CUBIC_INCHES_LOG_4 = "volumeCubicInchesLog4",
  VOLUME_CUBIC_INCHES_LOG_5 = "volumeCubicInchesLog5",
  VOLUME_CUBIC_FEET_LOG_0 = "volumeCubicFeetLog0",
  VOLUME_CUBIC_FEET_LOG_1 = "volumeCubicFeetLog1",
  VOLUME_CUBIC_FEET_LOG_2 = "volumeCubicFeetLog2",
  VOLUME_CUBIC_FEET_LOG_3 = "volumeCubicFeetLog3",
  VOLUME_CUBIC_FEET_LOG_4 = "volumeCubicFeetLog4",
  VOLUME_CUBIC_FEET_LOG_5 = "volumeCubicFeetLog5",
  VOLUME_CUBIC_YARDS_LOG_0 = "volumeCubicYardsLog0",
  VOLUME_CUBIC_YARDS_LOG_1 = "volumeCubicYardsLog1",
  VOLUME_CUBIC_YARDS_LOG_2 = "volumeCubicYardsLog2",
  VOLUME_CUBIC_YARDS_LOG_3 = "volumeCubicYardsLog3",
  VOLUME_CUBIC_YARDS_LOG_4 = "volumeCubicYardsLog4",
  VOLUME_CUBIC_YARDS_LOG_5 = "volumeCubicYardsLog5",
  COUNT = "count",
  AMOUNT_PAYABLE_0 = "amountPayable0",
  AMOUNT_PAYABLE_1 = "amountPayable1",
  AMOUNT_PAYABLE_2 = "amountPayable2",
  AMOUNT_PAYABLE_3 = "amountPayable3",
  AMOUNT_PAYABLE_4 = "amountPayable4",
  AMOUNT_PAYABLE_5 = "amountPayable5",
  AMOUNT_PAYABLE_ISO_0 = "amountPayableISO0",
  AMOUNT_PAYABLE_ISO_1 = "amountPayableISO1",
  AMOUNT_PAYABLE_ISO_2 = "amountPayableISO2",
  AMOUNT_PAYABLE_ISO_3 = "amountPayableISO3",
  AMOUNT_PAYABLE_ISO_4 = "amountPayableISO4",
  AMOUNT_PAYABLE_ISO_5 = "amountPayableISO5",
  PRICE_0 = "price0",
  PRICE_1 = "price1",
  PRICE_2 = "price2",
  PRICE_3 = "price3",
  PRICE_ISO_0 = "priceISO0",
  PRICE_ISO_1 = "priceISO1",
  PRICE_ISO_2 = "priceISO2",
  PRICE_ISO_3 = "priceISO3",
  PERCENT_DISCOUNT_0 = "percentDiscount0",
  PERCENT_DISCOUNT_1 = "percentDiscount1",
  PERCENT_DISCOUNT_2 = "percentDiscount2",
  PERCENT_DISCOUNT_3 = "percentDiscount3",
  PRICE_PER_UNIT_MEASURE_0 = "pricePerUnitMeasure0",
  PRICE_PER_UNIT_MEASURE_1 = "pricePerUnitMeasure1",
  PRICE_PER_UNIT_MEASURE_2 = "pricePerUnitMeasure2",
  PRICE_PER_UNIT_MEASURE_3 = "pricePerUnitMeasure3",
  PRICE_PER_UNIT_MEASURE_4 = "pricePerUnitMeasure4",
  PRICE_PER_UNIT_MEASURE_5 = "pricePerUnitMeasure5",
  ORDER_NUMBER = "orderNumber",
  GINC = "ginc",
  GSIN = "gsin",
  ROUTE = "route",
  SHIP_TO = "shipTo",
  BILL_TO = "billTo",
  PURCHASE_FROM = "purchaseFrom",
  SHIP_FOR = "shipFor",
  LOC_NO = "locNo",
  PAY_TO = "payTo",
  PROD_SERV_LOC = "prodServLoc",
  PARTY = "party",
  SHIP_TO_POST = "shipToPost",
  SHIP_TO_POST_ISO = "shipToPostISO",
  ORIGIN = "origin",
  COUNTRY_INITIAL_PROCESS = "countryInitialProcess",
  COUNTRY_PROCESS = "countryProcess",
  COUNTRY_DISASSEMBLY = "countryDisassembly",
  COUNTRY_FULL_PROCESS = "countryFullProcess",
  ORIGIN_SUBDIVISION = "originSubdivision",
  SHIP_TO_COMP = "shipToComp",
  SHIP_TO_NAME = "shipToName",
  SHIP_TO_ADD1 = "shipToAdd1",
  SHIP_TO_ADD2 = "shipToAdd2",
  SHIP_TO_SUB = "shipToSub",
  SHIP_TO_LOC = "shipToLoc",
  SHIP_TO_REG = "shipToReg",
  SHIP_TO_COUNTRY = "shipToCountry",
  SHIP_TO_PHONE = "shipToPhone",
  SHIP_TO_GEO = "shipToGeo",
  RTN_TO_COMP = "rtnToComp",
  RTN_TO_NAME = "rtnToName",
  RTN_TO_ADD1 = "rtnToAdd1",
  RTN_TO_ADD2 = "rtnToAdd2",
  RTN_TO_SUB = "rtnToSub",
  RTN_TO_LOC = "rtnToLoc",
  RTN_TO_REG = "rtnToReg",
  RTN_TO_COUNTRY = "rtnToCountry",
  RTN_TO_POST = "rtnToPost",
  RTN_TO_PHONE = "rtnToPhone",
  SRV_DESCRIPTION = "srvDescription",
  DANGEROUS_GOODS = "dangerousGoods",
  AUTH_LEAVE = "authLeave",
  SIG_REQUIRED = "sigRequired",
  NBEF_DEL_DT = "nbefDelDt",
  NAFT_DEL_DT = "naftDelDt",
  REL_DATE = "relDate",
  MAX_TEMP_F = "maxTempF",
  MAX_TEMP_C = "maxTempC",
  MIN_TEMP_F = "minTempF",
  MIN_TEMP_C = "minTempC",
  NSN = "nsn",
  MEAT_CUT = "meatCut",
  EXPIRATION_DATE_TIME = "expirationDateTime",
  ACTIVE_POTENCY = "activePotency",
  CATCH_AREA = "catchArea",
  FIRST_FREEZE_DATE = "firstFreezeDate",
  HARVEST_DATE = "harvestDate",
  AQUATIC_SPECIES = "aquaticSpecies",
  FISHING_GEAR_TYPE = "fishingGearType",
  PROD_METHOD = "prodMethod",
  REFURB_LOT = "refurbLot",
  FUNC_STAT = "funcStat",
  REV_STAT = "revStat",
  GIAI_ASSEMBLY = "giaiAssembly",
  PROCESSOR = "processor",
  PROCESSOR_2 = "processor2",
  PROCESSOR_3 = "processor3",
  PROCESSOR_4 = "processor4",
  PROCESSOR_5 = "processor5",
  PROCESSOR_6 = "processor6",
  PROCESSOR_7 = "processor7",
  PROCESSOR_8 = "processor8",
  PROCESSOR_9 = "processor9",
  PROCESSOR_10 = "processor10",
  UIC_EXT = "uicExt",
  UFRGT_UNIT_TYPE = "ufrgtUnitType",
  NHRN_PZN = "nhrnPzn",
  NHRN_CIP = "nhrnCip",
  NHRN_CN = "nhrnCn",
  NHRN_DRN = "nhrnDrn",
  NHRN_AIM = "nhrnAim",
  NHRN_DNC = "nhrnDnc",
  NHRN_AIC = "nhrnAic",
  ROLL_PRODUCTS = "rollProducts",
  CMT_NO = "cmtNo",
  GRAI = "grai",
  GIAI = "giai",
  PRICE_PER_UNIT = "pricePerUnit",
  ITIP = "itip",
  IBAN = "iban",
  PROD_TIME = "prodTime",
  OPTICAL_SENSOR = "opticalSensor",
  CPID = "cpid",
  CPID_SERIAL = "cpidSerial",
  VERSION = "version",
  GMN = "gmn",
  GSRN_PROVIDER = "gsrnProvider",
  GSRN_RECIPIENT = "gsrnRecipient",
  SRIN = "srin",
  REF_NO = "refNo",
  ITIP_CONTENT = "itipContent",
  DIG_SIG = "digSig",
  COUPON = "coupon",
  POINTS = "points",
  COUPON_EXTENDED = "couponExtended",
  PRODUCT_URL = "productURL",
  INTERNAL_1 = "internal1",
  INTERNAL_2 = "internal2",
  INTERNAL_3 = "internal3",
  INTERNAL_4 = "internal4",
  INTERNAL_5 = "internal5",
  INTERNAL_6 = "internal6",
  INTERNAL_7 = "internal7",
  INTERNAL_8 = "internal8",
  INTERNAL_9 = "internal9",
  INTERNAL_10 = "internal10",
}

export const AIMap: Record<string, GS1Field> = {
  ai00: GS1Field.SSCC,
  ai01: GS1Field.GTIN,
  ai02: GS1Field.CONTENT,
  ai10: GS1Field.BATCH,
  ai11: GS1Field.PROD_DATE,
  ai12: GS1Field.DUE_DATE,
  ai13: GS1Field.PACK_DATE,
  ai15: GS1Field.BEST_BEFORE,
  ai16: GS1Field.SELL_BY,
  ai17: GS1Field.EXP_DATE,
  ai20: GS1Field.VARIANT,
  ai21: GS1Field.SERIAL,
  ai22: GS1Field.HIBCC,
  ai235: GS1Field.TPX,
  ai240: GS1Field.ADDITIONAL_PRODUCT_ID,
  ai241: GS1Field.CUSTOMER_PART_NUMBER,
  ai242: GS1Field.MADE_TO_ORDER,
  ai243: GS1Field.PACKAGING,
  ai250: GS1Field.SECONDARY_SERIAL_NUMBER,
  ai251: GS1Field.REF_SOURCE,
  ai253: GS1Field.GDTI,
  ai254: GS1Field.GLN_EXTENSION,
  ai255: GS1Field.GCN,
  ai30: GS1Field.VARIABLE_COUNT,
  ai310: GS1Field.NET_WEIGHT_KG_0,
  ai3100: GS1Field.NET_WEIGHT_KG_0,
  ai3101: GS1Field.NET_WEIGHT_KG_1,
  ai3102: GS1Field.NET_WEIGHT_KG_2,
  ai3103: GS1Field.NET_WEIGHT_KG_3,
  ai3104: GS1Field.NET_WEIGHT_KG_4,
  ai3105: GS1Field.NET_WEIGHT_KG_5,
  ai3110: GS1Field.LENGTH_METERS_0,
  ai3111: GS1Field.LENGTH_METERS_1,
  ai3112: GS1Field.LENGTH_METERS_2,
  ai3113: GS1Field.LENGTH_METERS_3,
  ai3114: GS1Field.LENGTH_METERS_4,
  ai3115: GS1Field.LENGTH_METERS_5,
  ai3120: GS1Field.WIDTH_METERS_0,
  ai3121: GS1Field.WIDTH_METERS_1,
  ai3122: GS1Field.WIDTH_METERS_2,
  ai3123: GS1Field.WIDTH_METERS_3,
  ai3124: GS1Field.WIDTH_METERS_4,
  ai3125: GS1Field.WIDTH_METERS_5,
  ai3130: GS1Field.HEIGHT_METERS_0,
  ai3131: GS1Field.HEIGHT_METERS_1,
  ai3132: GS1Field.HEIGHT_METERS_2,
  ai3133: GS1Field.HEIGHT_METERS_3,
  ai3134: GS1Field.HEIGHT_METERS_4,
  ai3135: GS1Field.HEIGHT_METERS_5,
  ai3140: GS1Field.AREA_SQUARE_METERS_0,
  ai3141: GS1Field.AREA_SQUARE_METERS_1,
  ai3142: GS1Field.AREA_SQUARE_METERS_2,
  ai3143: GS1Field.AREA_SQUARE_METERS_3,
  ai3144: GS1Field.AREA_SQUARE_METERS_4,
  ai3145: GS1Field.AREA_SQUARE_METERS_5,
  ai3150: GS1Field.NET_VOLUME_LITERS_0,
  ai3151: GS1Field.NET_VOLUME_LITERS_1,
  ai3152: GS1Field.NET_VOLUME_LITERS_2,
  ai3153: GS1Field.NET_VOLUME_LITERS_3,
  ai3154: GS1Field.NET_VOLUME_LITERS_4,
  ai3155: GS1Field.NET_VOLUME_LITERS_5,
  ai3160: GS1Field.NET_VOLUME_CUBIC_METERS_0,
  ai3161: GS1Field.NET_VOLUME_CUBIC_METERS_1,
  ai3162: GS1Field.NET_VOLUME_CUBIC_METERS_2,
  ai3163: GS1Field.NET_VOLUME_CUBIC_METERS_3,
  ai3164: GS1Field.NET_VOLUME_CUBIC_METERS_4,
  ai3165: GS1Field.NET_VOLUME_CUBIC_METERS_5,
  ai3200: GS1Field.NET_WEIGHT_LB_0,
  ai3201: GS1Field.NET_WEIGHT_LB_1,
  ai3202: GS1Field.NET_WEIGHT_LB_2,
  ai3203: GS1Field.NET_WEIGHT_LB_3,
  ai3204: GS1Field.NET_WEIGHT_LB_4,
  ai3205: GS1Field.NET_WEIGHT_LB_5,
  ai3210: GS1Field.LENGTH_INCHES_0,
  ai3211: GS1Field.LENGTH_INCHES_1,
  ai3212: GS1Field.LENGTH_INCHES_2,
  ai3213: GS1Field.LENGTH_INCHES_3,
  ai3214: GS1Field.LENGTH_INCHES_4,
  ai3215: GS1Field.LENGTH_INCHES_5,
  ai3220: GS1Field.LENGTH_FEET_0,
  ai3221: GS1Field.LENGTH_FEET_1,
  ai3222: GS1Field.LENGTH_FEET_2,
  ai3223: GS1Field.LENGTH_FEET_3,
  ai3224: GS1Field.LENGTH_FEET_4,
  ai3225: GS1Field.LENGTH_FEET_5,
  ai3230: GS1Field.LENGTH_YARDS_0,
  ai3231: GS1Field.LENGTH_YARDS_1,
  ai3232: GS1Field.LENGTH_YARDS_2,
  ai3233: GS1Field.LENGTH_YARDS_3,
  ai3234: GS1Field.LENGTH_YARDS_4,
  ai3235: GS1Field.LENGTH_YARDS_5,
  ai3240: GS1Field.WIDTH_INCHES_0,
  ai3241: GS1Field.WIDTH_INCHES_1,
  ai3242: GS1Field.WIDTH_INCHES_2,
  ai3243: GS1Field.WIDTH_INCHES_3,
  ai3244: GS1Field.WIDTH_INCHES_4,
  ai3245: GS1Field.WIDTH_INCHES_5,
  ai3250: GS1Field.WIDTH_FEET_0,
  ai3251: GS1Field.WIDTH_FEET_1,
  ai3252: GS1Field.WIDTH_FEET_2,
  ai3253: GS1Field.WIDTH_FEET_3,
  ai3254: GS1Field.WIDTH_FEET_4,
  ai3255: GS1Field.WIDTH_FEET_5,
  ai3260: GS1Field.WIDTH_YARDS_0,
  ai3261: GS1Field.WIDTH_YARDS_1,
  ai3262: GS1Field.WIDTH_YARDS_2,
  ai3263: GS1Field.WIDTH_YARDS_3,
  ai3264: GS1Field.WIDTH_YARDS_4,
  ai3265: GS1Field.WIDTH_YARDS_5,
  ai3270: GS1Field.HEIGHT_INCHES_0,
  ai3271: GS1Field.HEIGHT_INCHES_1,
  ai3272: GS1Field.HEIGHT_INCHES_2,
  ai3273: GS1Field.HEIGHT_INCHES_3,
  ai3274: GS1Field.HEIGHT_INCHES_4,
  ai3275: GS1Field.HEIGHT_INCHES_5,
  ai3280: GS1Field.HEIGHT_FEET_0,
  ai3281: GS1Field.HEIGHT_FEET_1,
  ai3282: GS1Field.HEIGHT_FEET_2,
  ai3283: GS1Field.HEIGHT_FEET_3,
  ai3284: GS1Field.HEIGHT_FEET_4,
  ai3285: GS1Field.HEIGHT_FEET_5,
  ai3290: GS1Field.HEIGHT_YARDS_0,
  ai3291: GS1Field.HEIGHT_YARDS_1,
  ai3292: GS1Field.HEIGHT_YARDS_2,
  ai3293: GS1Field.HEIGHT_YARDS_3,
  ai3294: GS1Field.HEIGHT_YARDS_4,
  ai3295: GS1Field.HEIGHT_YARDS_5,
  ai3300: GS1Field.GROSS_WEIGHT_KG_0,
  ai3301: GS1Field.GROSS_WEIGHT_KG_1,
  ai3302: GS1Field.GROSS_WEIGHT_KG_2,
  ai3303: GS1Field.GROSS_WEIGHT_KG_3,
  ai3304: GS1Field.GROSS_WEIGHT_KG_4,
  ai3305: GS1Field.GROSS_WEIGHT_KG_5,
  ai3310: GS1Field.LENGTH_METERS_LOG_0,
  ai3311: GS1Field.LENGTH_METERS_LOG_1,
  ai3312: GS1Field.LENGTH_METERS_LOG_2,
  ai3313: GS1Field.LENGTH_METERS_LOG_3,
  ai3314: GS1Field.LENGTH_METERS_LOG_4,
  ai3315: GS1Field.LENGTH_METERS_LOG_5,
  ai3320: GS1Field.WIDTH_METERS_LOG_0,
  ai3321: GS1Field.WIDTH_METERS_LOG_1,
  ai3322: GS1Field.WIDTH_METERS_LOG_2,
  ai3323: GS1Field.WIDTH_METERS_LOG_3,
  ai3324: GS1Field.WIDTH_METERS_LOG_4,
  ai3325: GS1Field.WIDTH_METERS_LOG_5,
  ai3330: GS1Field.HEIGHT_METERS_LOG_0,
  ai3331: GS1Field.HEIGHT_METERS_LOG_1,
  ai3332: GS1Field.HEIGHT_METERS_LOG_2,
  ai3333: GS1Field.HEIGHT_METERS_LOG_3,
  ai3334: GS1Field.HEIGHT_METERS_LOG_4,
  ai3335: GS1Field.HEIGHT_METERS_LOG_5,
  ai3340: GS1Field.AREA_SQUARE_INCHES_0,
  ai3341: GS1Field.AREA_SQUARE_INCHES_1,
  ai3342: GS1Field.AREA_SQUARE_INCHES_2,
  ai3343: GS1Field.AREA_SQUARE_INCHES_3,
  ai3344: GS1Field.AREA_SQUARE_INCHES_4,
  ai3345: GS1Field.AREA_SQUARE_INCHES_5,
  ai3350: GS1Field.AREA_SQUARE_FEET_0,
  ai3351: GS1Field.AREA_SQUARE_FEET_1,
  ai3352: GS1Field.AREA_SQUARE_FEET_2,
  ai3353: GS1Field.AREA_SQUARE_FEET_3,
  ai3354: GS1Field.AREA_SQUARE_FEET_4,
  ai3355: GS1Field.AREA_SQUARE_FEET_5,
  ai3360: GS1Field.AREA_SQUARE_YARDS_0,
  ai3361: GS1Field.AREA_SQUARE_YARDS_1,
  ai3362: GS1Field.AREA_SQUARE_YARDS_2,
  ai3363: GS1Field.AREA_SQUARE_YARDS_3,
  ai3364: GS1Field.AREA_SQUARE_YARDS_4,
  ai3365: GS1Field.AREA_SQUARE_YARDS_5,
  ai3370: GS1Field.AREA_SQUARE_METERS_LOG_0,
  ai3371: GS1Field.AREA_SQUARE_METERS_LOG_1,
  ai3372: GS1Field.AREA_SQUARE_METERS_LOG_2,
  ai3373: GS1Field.AREA_SQUARE_METERS_LOG_3,
  ai3374: GS1Field.AREA_SQUARE_METERS_LOG_4,
  ai3375: GS1Field.AREA_SQUARE_METERS_LOG_5,
  ai3400: GS1Field.NET_WEIGHT_OUNCES_0,
  ai3401: GS1Field.NET_WEIGHT_OUNCES_1,
  ai3402: GS1Field.NET_WEIGHT_OUNCES_2,
  ai3403: GS1Field.NET_WEIGHT_OUNCES_3,
  ai3404: GS1Field.NET_WEIGHT_OUNCES_4,
  ai3405: GS1Field.NET_WEIGHT_OUNCES_5,
  ai3410: GS1Field.NET_VOLUME_QUARTS_0,
  ai3411: GS1Field.NET_VOLUME_QUARTS_1,
  ai3412: GS1Field.NET_VOLUME_QUARTS_2,
  ai3413: GS1Field.NET_VOLUME_QUARTS_3,
  ai3414: GS1Field.NET_VOLUME_QUARTS_4,
  ai3415: GS1Field.NET_VOLUME_QUARTS_5,
  ai3420: GS1Field.NET_VOLUME_GALLONS_0,
  ai3421: GS1Field.NET_VOLUME_GALLONS_1,
  ai3422: GS1Field.NET_VOLUME_GALLONS_2,
  ai3423: GS1Field.NET_VOLUME_GALLONS_3,
  ai3424: GS1Field.NET_VOLUME_GALLONS_4,
  ai3425: GS1Field.NET_VOLUME_GALLONS_5,
  ai3430: GS1Field.VOLUME_CUBIC_INCHES_0,
  ai3431: GS1Field.VOLUME_CUBIC_INCHES_1,
  ai3432: GS1Field.VOLUME_CUBIC_INCHES_2,
  ai3433: GS1Field.VOLUME_CUBIC_INCHES_3,
  ai3434: GS1Field.VOLUME_CUBIC_INCHES_4,
  ai3435: GS1Field.VOLUME_CUBIC_INCHES_5,
  ai3440: GS1Field.VOLUME_CUBIC_FEET_0,
  ai3441: GS1Field.VOLUME_CUBIC_FEET_1,
  ai3442: GS1Field.VOLUME_CUBIC_FEET_2,
  ai3443: GS1Field.VOLUME_CUBIC_FEET_3,
  ai3444: GS1Field.VOLUME_CUBIC_FEET_4,
  ai3445: GS1Field.VOLUME_CUBIC_FEET_5,
  ai3450: GS1Field.VOLUME_CUBIC_YARDS_0,
  ai3451: GS1Field.VOLUME_CUBIC_YARDS_1,
  ai3452: GS1Field.VOLUME_CUBIC_YARDS_2,
  ai3453: GS1Field.VOLUME_CUBIC_YARDS_3,
  ai3454: GS1Field.VOLUME_CUBIC_YARDS_4,
  ai3455: GS1Field.VOLUME_CUBIC_YARDS_5,
  ai3460: GS1Field.VOLUME_CUBIC_METERS_LOG_0,
  ai3461: GS1Field.VOLUME_CUBIC_METERS_LOG_1,
  ai3462: GS1Field.VOLUME_CUBIC_METERS_LOG_2,
  ai3463: GS1Field.VOLUME_CUBIC_METERS_LOG_3,
  ai3464: GS1Field.VOLUME_CUBIC_METERS_LOG_4,
  ai3465: GS1Field.VOLUME_CUBIC_METERS_LOG_5,
  ai3500: GS1Field.GROSS_WEIGHT_LB_0,
  ai3501: GS1Field.GROSS_WEIGHT_LB_1,
  ai3502: GS1Field.GROSS_WEIGHT_LB_2,
  ai3503: GS1Field.GROSS_WEIGHT_LB_3,
  ai3504: GS1Field.GROSS_WEIGHT_LB_4,
  ai3505: GS1Field.GROSS_WEIGHT_LB_5,
  ai3510: GS1Field.LENGTH_INCHES_LOG_0,
  ai3511: GS1Field.LENGTH_INCHES_LOG_1,
  ai3512: GS1Field.LENGTH_INCHES_LOG_2,
  ai3513: GS1Field.LENGTH_INCHES_LOG_3,
  ai3514: GS1Field.LENGTH_INCHES_LOG_4,
  ai3515: GS1Field.LENGTH_INCHES_LOG_5,
  ai3520: GS1Field.LENGTH_FEET_LOG_0,
  ai3521: GS1Field.LENGTH_FEET_LOG_1,
  ai3522: GS1Field.LENGTH_FEET_LOG_2,
  ai3523: GS1Field.LENGTH_FEET_LOG_3,
  ai3524: GS1Field.LENGTH_FEET_LOG_4,
  ai3525: GS1Field.LENGTH_FEET_LOG_5,
  ai3530: GS1Field.LENGTH_YARDS_LOG_0,
  ai3531: GS1Field.LENGTH_YARDS_LOG_1,
  ai3532: GS1Field.LENGTH_YARDS_LOG_2,
  ai3533: GS1Field.LENGTH_YARDS_LOG_3,
  ai3534: GS1Field.LENGTH_YARDS_LOG_4,
  ai3535: GS1Field.LENGTH_YARDS_LOG_5,
  ai3540: GS1Field.WIDTH_INCHES_LOG_0,
  ai3541: GS1Field.WIDTH_INCHES_LOG_1,
  ai3542: GS1Field.WIDTH_INCHES_LOG_2,
  ai3543: GS1Field.WIDTH_INCHES_LOG_3,
  ai3544: GS1Field.WIDTH_INCHES_LOG_4,
  ai3545: GS1Field.WIDTH_INCHES_LOG_5,
  ai3550: GS1Field.WIDTH_FEET_LOG_0,
  ai3551: GS1Field.WIDTH_FEET_LOG_1,
  ai3552: GS1Field.WIDTH_FEET_LOG_2,
  ai3553: GS1Field.WIDTH_FEET_LOG_3,
  ai3554: GS1Field.WIDTH_FEET_LOG_4,
  ai3555: GS1Field.WIDTH_FEET_LOG_5,
  ai3560: GS1Field.WIDTH_YARDS_LOG_0,
  ai3561: GS1Field.WIDTH_YARDS_LOG_1,
  ai3562: GS1Field.WIDTH_YARDS_LOG_2,
  ai3563: GS1Field.WIDTH_YARDS_LOG_3,
  ai3564: GS1Field.WIDTH_YARDS_LOG_4,
  ai3565: GS1Field.WIDTH_YARDS_LOG_5,
  ai3570: GS1Field.HEIGHT_INCHES_LOG_0,
  ai3571: GS1Field.HEIGHT_INCHES_LOG_1,
  ai3572: GS1Field.HEIGHT_INCHES_LOG_2,
  ai3573: GS1Field.HEIGHT_INCHES_LOG_3,
  ai3574: GS1Field.HEIGHT_INCHES_LOG_4,
  ai3575: GS1Field.HEIGHT_INCHES_LOG_5,
  ai3580: GS1Field.HEIGHT_FEET_LOG_0,
  ai3581: GS1Field.HEIGHT_FEET_LOG_1,
  ai3582: GS1Field.HEIGHT_FEET_LOG_2,
  ai3583: GS1Field.HEIGHT_FEET_LOG_3,
  ai3584: GS1Field.HEIGHT_FEET_LOG_4,
  ai3585: GS1Field.HEIGHT_FEET_LOG_5,
  ai3590: GS1Field.HEIGHT_YARDS_LOG_0,
  ai3591: GS1Field.HEIGHT_YARDS_LOG_1,
  ai3592: GS1Field.HEIGHT_YARDS_LOG_2,
  ai3593: GS1Field.HEIGHT_YARDS_LOG_3,
  ai3594: GS1Field.HEIGHT_YARDS_LOG_4,
  ai3595: GS1Field.HEIGHT_YARDS_LOG_5,
  ai3600: GS1Field.GROSS_WEIGHT_OUNCES_0,
  ai3601: GS1Field.GROSS_WEIGHT_OUNCES_1,
  ai3602: GS1Field.GROSS_WEIGHT_OUNCES_2,
  ai3603: GS1Field.GROSS_WEIGHT_OUNCES_3,
  ai3604: GS1Field.GROSS_WEIGHT_OUNCES_4,
  ai3605: GS1Field.GROSS_WEIGHT_OUNCES_5,
  ai3610: GS1Field.NET_VOLUME_FLUID_OUNCES_0,
  ai3611: GS1Field.NET_VOLUME_FLUID_OUNCES_1,
  ai3612: GS1Field.NET_VOLUME_FLUID_OUNCES_2,
  ai3613: GS1Field.NET_VOLUME_FLUID_OUNCES_3,
  ai3614: GS1Field.NET_VOLUME_FLUID_OUNCES_4,
  ai3615: GS1Field.NET_VOLUME_FLUID_OUNCES_5,
  ai3620: GS1Field.GROSS_VOLUME_QUARTS_0,
  ai3621: GS1Field.GROSS_VOLUME_QUARTS_1,
  ai3622: GS1Field.GROSS_VOLUME_QUARTS_2,
  ai3623: GS1Field.GROSS_VOLUME_QUARTS_3,
  ai3624: GS1Field.GROSS_VOLUME_QUARTS_4,
  ai3625: GS1Field.GROSS_VOLUME_QUARTS_5,
  ai3630: GS1Field.GROSS_VOLUME_GALLONS_0,
  ai3631: GS1Field.GROSS_VOLUME_GALLONS_1,
  ai3632: GS1Field.GROSS_VOLUME_GALLONS_2,
  ai3633: GS1Field.GROSS_VOLUME_GALLONS_3,
  ai3634: GS1Field.GROSS_VOLUME_GALLONS_4,
  ai3635: GS1Field.GROSS_VOLUME_GALLONS_5,
  ai3640: GS1Field.VOLUME_CUBIC_INCHES_LOG_0,
  ai3641: GS1Field.VOLUME_CUBIC_INCHES_LOG_1,
  ai3642: GS1Field.VOLUME_CUBIC_INCHES_LOG_2,
  ai3643: GS1Field.VOLUME_CUBIC_INCHES_LOG_3,
  ai3644: GS1Field.VOLUME_CUBIC_INCHES_LOG_4,
  ai3645: GS1Field.VOLUME_CUBIC_INCHES_LOG_5,
  ai3650: GS1Field.VOLUME_CUBIC_FEET_LOG_0,
  ai3651: GS1Field.VOLUME_CUBIC_FEET_LOG_1,
  ai3652: GS1Field.VOLUME_CUBIC_FEET_LOG_2,
  ai3653: GS1Field.VOLUME_CUBIC_FEET_LOG_3,
  ai3654: GS1Field.VOLUME_CUBIC_FEET_LOG_4,
  ai3655: GS1Field.VOLUME_CUBIC_FEET_LOG_5,
  ai3660: GS1Field.VOLUME_CUBIC_YARDS_LOG_0,
  ai3661: GS1Field.VOLUME_CUBIC_YARDS_LOG_1,
  ai3662: GS1Field.VOLUME_CUBIC_YARDS_LOG_2,
  ai3663: GS1Field.VOLUME_CUBIC_YARDS_LOG_3,
  ai3664: GS1Field.VOLUME_CUBIC_YARDS_LOG_4,
  ai3665: GS1Field.VOLUME_CUBIC_YARDS_LOG_5,
  ai37: GS1Field.COUNT,
  ai3900: GS1Field.AMOUNT_PAYABLE_0,
  ai3901: GS1Field.AMOUNT_PAYABLE_1,
  ai3902: GS1Field.AMOUNT_PAYABLE_2,
  ai3903: GS1Field.AMOUNT_PAYABLE_3,
  ai3904: GS1Field.AMOUNT_PAYABLE_4,
  ai3905: GS1Field.AMOUNT_PAYABLE_5,
  ai3910: GS1Field.AMOUNT_PAYABLE_ISO_0,
  ai3911: GS1Field.AMOUNT_PAYABLE_ISO_1,
  ai3912: GS1Field.AMOUNT_PAYABLE_ISO_2,
  ai3913: GS1Field.AMOUNT_PAYABLE_ISO_3,
  ai3914: GS1Field.AMOUNT_PAYABLE_ISO_4,
  ai3915: GS1Field.AMOUNT_PAYABLE_ISO_5,
  ai3920: GS1Field.PRICE_0,
  ai3921: GS1Field.PRICE_1,
  ai3922: GS1Field.PRICE_2,
  ai3923: GS1Field.PRICE_3,
  ai3930: GS1Field.PRICE_ISO_0,
  ai3931: GS1Field.PRICE_ISO_1,
  ai3932: GS1Field.PRICE_ISO_2,
  ai3933: GS1Field.PRICE_ISO_3,
  ai3940: GS1Field.PERCENT_DISCOUNT_0,
  ai3941: GS1Field.PERCENT_DISCOUNT_1,
  ai3942: GS1Field.PERCENT_DISCOUNT_2,
  ai3943: GS1Field.PERCENT_DISCOUNT_3,
  ai3950: GS1Field.PRICE_PER_UNIT_MEASURE_0,
  ai3951: GS1Field.PRICE_PER_UNIT_MEASURE_1,
  ai3952: GS1Field.PRICE_PER_UNIT_MEASURE_2,
  ai3953: GS1Field.PRICE_PER_UNIT_MEASURE_3,
  ai3954: GS1Field.PRICE_PER_UNIT_MEASURE_4,
  ai3955: GS1Field.PRICE_PER_UNIT_MEASURE_5,
  ai400: GS1Field.ORDER_NUMBER,
  ai401: GS1Field.GINC,
  ai402: GS1Field.GSIN,
  ai403: GS1Field.ROUTE,
  ai410: GS1Field.SHIP_TO,
  ai411: GS1Field.BILL_TO,
  ai412: GS1Field.PURCHASE_FROM,
  ai413: GS1Field.SHIP_FOR,
  ai414: GS1Field.LOC_NO,
  ai415: GS1Field.PAY_TO,
  ai416: GS1Field.PROD_SERV_LOC,
  ai417: GS1Field.PARTY,
  ai420: GS1Field.SHIP_TO_POST,
  ai421: GS1Field.SHIP_TO_POST_ISO,
  ai422: GS1Field.ORIGIN,
  ai423: GS1Field.COUNTRY_INITIAL_PROCESS,
  ai424: GS1Field.COUNTRY_PROCESS,
  ai425: GS1Field.COUNTRY_DISASSEMBLY,
  ai426: GS1Field.COUNTRY_FULL_PROCESS,
  ai427: GS1Field.ORIGIN_SUBDIVISION,
  ai4300: GS1Field.SHIP_TO_COMP,
  ai4301: GS1Field.SHIP_TO_NAME,
  ai4302: GS1Field.SHIP_TO_ADD1,
  ai4303: GS1Field.SHIP_TO_ADD2,
  ai4304: GS1Field.SHIP_TO_SUB,
  ai4305: GS1Field.SHIP_TO_LOC,
  ai4306: GS1Field.SHIP_TO_REG,
  ai4307: GS1Field.SHIP_TO_COUNTRY,
  ai4308: GS1Field.SHIP_TO_PHONE,
  ai4309: GS1Field.SHIP_TO_GEO,
  ai4310: GS1Field.RTN_TO_COMP,
  ai4311: GS1Field.RTN_TO_NAME,
  ai4312: GS1Field.RTN_TO_ADD1,
  ai4313: GS1Field.RTN_TO_ADD2,
  ai4314: GS1Field.RTN_TO_SUB,
  ai4315: GS1Field.RTN_TO_LOC,
  ai4316: GS1Field.RTN_TO_REG,
  ai4317: GS1Field.RTN_TO_COUNTRY,
  ai4318: GS1Field.RTN_TO_POST,
  ai4319: GS1Field.RTN_TO_PHONE,
  ai4320: GS1Field.SRV_DESCRIPTION,
  ai4321: GS1Field.DANGEROUS_GOODS,
  ai4322: GS1Field.AUTH_LEAVE,
  ai4323: GS1Field.SIG_REQUIRED,
  ai4324: GS1Field.NBEF_DEL_DT,
  ai4325: GS1Field.NAFT_DEL_DT,
  ai4326: GS1Field.REL_DATE,
  ai4330: GS1Field.MAX_TEMP_F,
  ai4331: GS1Field.MAX_TEMP_C,
  ai4332: GS1Field.MIN_TEMP_F,
  ai4333: GS1Field.MIN_TEMP_C,
  ai7001: GS1Field.NSN,
  ai7002: GS1Field.MEAT_CUT,
  ai7003: GS1Field.EXPIRATION_DATE_TIME,
  ai7004: GS1Field.ACTIVE_POTENCY,
  ai7005: GS1Field.CATCH_AREA,
  ai7006: GS1Field.FIRST_FREEZE_DATE,
  ai7007: GS1Field.HARVEST_DATE,
  ai7008: GS1Field.AQUATIC_SPECIES,
  ai7009: GS1Field.FISHING_GEAR_TYPE,
  ai7010: GS1Field.PROD_METHOD,
  ai7020: GS1Field.REFURB_LOT,
  ai7021: GS1Field.FUNC_STAT,
  ai7022: GS1Field.REV_STAT,
  ai7023: GS1Field.GIAI_ASSEMBLY,
  ai7030: GS1Field.PROCESSOR,
  ai7031: GS1Field.PROCESSOR_2,
  ai7032: GS1Field.PROCESSOR_3,
  ai7033: GS1Field.PROCESSOR_4,
  ai7034: GS1Field.PROCESSOR_5,
  ai7035: GS1Field.PROCESSOR_6,
  ai7036: GS1Field.PROCESSOR_7,
  ai7037: GS1Field.PROCESSOR_8,
  ai7038: GS1Field.PROCESSOR_9,
  ai7039: GS1Field.PROCESSOR_10,
  ai7040: GS1Field.UIC_EXT,
  ai7041: GS1Field.UFRGT_UNIT_TYPE,
  ai710: GS1Field.NHRN_PZN,
  ai711: GS1Field.NHRN_CIP,
  ai712: GS1Field.NHRN_CN,
  ai713: GS1Field.NHRN_DRN,
  ai714: GS1Field.NHRN_AIM,
  ai715: GS1Field.NHRN_DNC,
  ai716: GS1Field.NHRN_AIC,
  ai8001: GS1Field.ROLL_PRODUCTS,
  ai8002: GS1Field.CMT_NO,
  ai8003: GS1Field.GRAI,
  ai8004: GS1Field.GIAI,
  ai8005: GS1Field.PRICE_PER_UNIT,
  ai8006: GS1Field.ITIP,
  ai8007: GS1Field.IBAN,
  ai8008: GS1Field.PROD_TIME,
  ai8009: GS1Field.OPTICAL_SENSOR,
  ai8010: GS1Field.CPID,
  ai8011: GS1Field.CPID_SERIAL,
  ai8012: GS1Field.VERSION,
  ai8013: GS1Field.GMN,
  ai8017: GS1Field.GSRN_PROVIDER,
  ai8018: GS1Field.GSRN_RECIPIENT,
  ai8019: GS1Field.SRIN,
  ai8020: GS1Field.REF_NO,
  ai8026: GS1Field.ITIP_CONTENT,
  ai8030: GS1Field.DIG_SIG,
  ai8110: GS1Field.COUPON,
  ai8111: GS1Field.POINTS,
  ai8112: GS1Field.COUPON_EXTENDED,
  ai8200: GS1Field.PRODUCT_URL,
  ai90: GS1Field.INTERNAL_1,
  ai91: GS1Field.INTERNAL_2,
  ai92: GS1Field.INTERNAL_3,
  ai93: GS1Field.INTERNAL_4,
  ai94: GS1Field.INTERNAL_5,
  ai95: GS1Field.INTERNAL_6,
  ai96: GS1Field.INTERNAL_7,
  ai97: GS1Field.INTERNAL_8,
  ai98: GS1Field.INTERNAL_9,
  ai99: GS1Field.INTERNAL_10,
};
